import React from 'react';

function Home()  {
    return(
        <div>
            <h1>Amit Bhattacharya</h1>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur est leo, lobortis sit amet aliquet in, faucibus et ex. Proin at diam sit amet justo convallis volutpat nec eget orci. Nunc vitae nunc facilisis, elementum augue et, fringilla eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam dignissim ex eget ante lobortis pretium. Donec accumsan erat ac tellus egestas, sed lacinia mi laoreet. Vestibulum vitae ex sit amet neque pharetra euismod. Suspendisse elementum vitae velit in pulvinar. Vestibulum elementum metus et sem feugiat viverra at nec ex. Nulla sagittis ex laoreet eleifend facilisis.

Pellentesque nec hendrerit nisi. Cras viverra malesuada lacus id faucibus. Curabitur id semper risus. Vestibulum posuere et nulla vel viverra. Etiam pretium non massa nec tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sit amet consequat diam. Etiam ultricies lectus est, nec euismod turpis gravida ut. Ut commodo purus ex. Phasellus tincidunt lectus ut finibus aliquet. Praesent iaculis rutrum erat et ultricies. Aliquam imperdiet augue a lectus dapibus cursus. Nunc at ex et nisi mollis pretium.

Quisque consectetur nisl ante, ut commodo ex malesuada eu. Donec eget convallis purus. Mauris tempus justo sit amet nisl ornare mattis. Pellentesque porta vitae elit ac bibendum. Ut varius lorem eu felis egestas tristique. Pellentesque efficitur, neque a consectetur placerat, nisi erat aliquam tortor, eget congue quam nisi vitae tortor. Etiam efficitur tortor at ante consequat, ac vulputate nisi consectetur. Nullam non enim molestie, elementum libero eget, blandit eros. Nullam arcu risus, fermentum a consectetur lacinia, ultrices at risus. Phasellus fringilla nisi id quam scelerisque, et euismod magna pharetra. Aenean pellentesque, neque placerat luctus fermentum, turpis mi posuere turpis, scelerisque viverra quam urna nec odio. Proin eu magna et libero feugiat congue. Curabitur mattis lobortis dolor nec sagittis. Nam ut auctor odio.

Maecenas ac consequat erat. Praesent lobortis, magna eu sodales blandit, sem mauris elementum risus, sit amet convallis metus felis ac mi. Vivamus non scelerisque velit, eget convallis mi. Sed vitae dui malesuada, mollis sapien a, sollicitudin urna. Aenean varius quam sit amet dui tempor, at ultricies ex euismod. Integer a enim et lacus pretium vulputate. Pellentesque nisl turpis, fringilla quis vehicula at, maximus eu diam.

Nunc placerat elit ac felis dictum, quis faucibus diam pharetra. Vivamus cursus, dui vitae accumsan porta, elit elit lobortis enim, eget commodo nisl nisi sit amet enim. Vestibulum sem diam, vulputate iaculis fermentum ut, tristique nec augue. Pellentesque suscipit quam nisl, eu tristique felis sollicitudin sed. Maecenas eu vehicula purus. Praesent sodales odio a elit egestas porta sit amet eu dolor. Phasellus quam est, efficitur sollicitudin scelerisque blandit, tempor eu arcu. Sed placerat vulputate quam. Fusce accumsan, ex id luctus porta, justo ipsum pulvinar lectus, a egestas enim purus eget dui. Fusce ut nulla elit. Mauris quis leo scelerisque massa gravida aliquet. Donec lacinia odio quis congue porta.

Vivamus pellentesque ex id tellus viverra, id feugiat justo vestibulum. Quisque et luctus lorem. Duis blandit semper tortor. Integer malesuada aliquet consequat. Vivamus hendrerit ante diam, eu blandit enim mollis vel. Ut at est eget erat sollicitudin maximus. Proin pellentesque ultricies lacus, id fringilla leo auctor nec. Donec sodales tortor id fermentum vestibulum. Phasellus eleifend id orci at auctor.

Praesent nec maximus mi, et dignissim sapien. Curabitur dapibus auctor orci, quis porta nulla laoreet id. Phasellus interdum quis neque ac sollicitudin. Praesent nec mattis quam. Proin molestie ante quis metus porta, vel congue sapien tristique. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec nulla sem, gravida sit amet elit vel, lacinia gravida ante. Nulla id porttitor ante. Mauris orci nisl, dignissim sed placerat vitae, volutpat vitae purus. In vulputate blandit elit vel ultricies. In hac habitasse platea dictumst.

Fusce rhoncus dapibus diam, eu porttitor velit fermentum vitae. In hac habitasse platea dictumst. Nullam eget turpis id lacus finibus dignissim in at purus. Maecenas malesuada volutpat turpis, et congue dui vestibulum at. Integer commodo scelerisque odio, eget laoreet arcu mollis sed. Integer vulputate purus nisi, ac porta justo mattis vitae. Aliquam commodo sed dolor vitae laoreet. Quisque euismod, quam fermentum efficitur euismod, nisl lacus cursus nisi, at aliquam nisi nunc sit amet nisl. Integer tincidunt venenatis felis eget tincidunt. Pellentesque consequat augue diam, ac lobortis lectus faucibus non. Duis nec varius turpis, in venenatis ligula. In lobortis iaculis condimentum.

Sed in sagittis erat. Sed maximus ac felis et scelerisque. Quisque interdum urna nisi, ut blandit elit lobortis nec. Sed posuere justo ut leo faucibus efficitur lobortis et mauris. Integer cursus felis a augue egestas blandit. Cras nec lacinia augue, quis rutrum lorem. Donec pulvinar quam ante, vel tincidunt metus aliquet ut. Sed aliquam purus in turpis imperdiet condimentum. In maximus leo egestas laoreet iaculis. Sed efficitur, lectus eget ornare viverra, risus ex ullamcorper felis, tempus rhoncus neque neque non felis.

Pellentesque tempus imperdiet mauris eget eleifend. Suspendisse blandit tortor mauris, non egestas ex eleifend vitae. Cras scelerisque vel turpis sed lobortis. Ut diam augue, tempor ut suscipit vel, commodo nec risus. Etiam eget metus nisl. Proin blandit, massa ut ullamcorper aliquam, urna ante viverra orci, sed suscipit mi nulla at justo. Nullam mattis velit sed sapien dictum, ac vulputate nulla scelerisque. Duis quam lorem, lacinia id tellus et, rhoncus hendrerit ipsum. Duis ullamcorper sodales ipsum, nec dignissim purus fringilla at. Quisque gravida elit consectetur, finibus massa at, ultricies ante.

Integer molestie sed quam ac sodales. Aliquam euismod risus eget dictum fringilla. Sed efficitur libero vitae tristique tincidunt. Proin gravida suscipit tempus. Duis at dictum odio, ut finibus odio. Vivamus ut dolor non nunc rhoncus varius a non urna. Vestibulum urna magna, interdum non dui id, consequat volutpat urna.

Cras rhoncus diam sed libero vulputate, at congue leo hendrerit. Praesent efficitur lacus in arcu malesuada faucibus. Vestibulum ultricies ultricies viverra. Praesent sit amet lectus eget elit vehicula malesuada et nec quam. Aliquam eu eros ut tortor fringilla finibus. Nullam ornare in lorem id fermentum. Vivamus efficitur mauris non eros tempus ultricies. Pellentesque nunc purus, aliquet et aliquet ac, sodales eget orci. In luctus faucibus ex, ac maximus nibh gravida sed. Duis vel leo et nulla convallis semper. Vivamus condimentum luctus volutpat. Ut lobortis condimentum eleifend. Pellentesque fermentum turpis ut pulvinar blandit. Nulla cursus dolor eros, vel consectetur elit posuere non. Vestibulum bibendum velit lacus, eu tempus magna tincidunt sit amet.

Morbi viverra, justo quis eleifend ullamcorper, tellus ex ornare ligula, a posuere metus dui sed lacus. Aenean viverra luctus lectus et dignissim. Donec volutpat dolor ut urna volutpat, a mollis ex sollicitudin. Sed turpis nibh, dictum sed quam in, dictum iaculis magna. Cras sit amet maximus sapien, et rutrum ante. Nam tincidunt tincidunt ligula sit amet tempor. Morbi bibendum quis arcu condimentum vulputate. Integer in luctus diam. Aliquam vehicula tempor hendrerit. Pellentesque iaculis turpis ut neque convallis, a luctus justo suscipit. Proin et enim tempus, mollis leo eu, commodo mauris. Curabitur suscipit egestas consectetur. Praesent molestie malesuada ligula vitae faucibus. Sed at libero dui.

Morbi sit amet ligula in ligula placerat ultricies. Suspendisse sodales velit sit amet pulvinar fringilla. Morbi at congue nulla. Pellentesque viverra venenatis metus, nec maximus arcu. Integer ac tellus non nunc pulvinar elementum in vitae velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sed vestibulum velit. Vestibulum ac condimentum mauris. Praesent in placerat felis. Praesent sed semper quam. Cras gravida finibus elit, vitae consequat velit cursus eget. Nullam ac justo non nisi tristique convallis at ac nulla. Sed finibus eleifend odio id fermentum. Donec hendrerit ipsum vitae lacus lacinia, rhoncus condimentum leo laoreet. Vivamus non volutpat nunc, et finibus nunc.

Etiam tellus mi, viverra eget diam eu, aliquam auctor purus. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dignissim risus id luctus sollicitudin. Vivamus vitae lacus turpis. Vivamus sed suscipit massa. Fusce at hendrerit urna. Ut congue lectus lacus. Vivamus euismod cursus mi quis dapibus. Duis lacinia ante quis lacinia rutrum
            </p>
        </div>
    )
}


export default Home;